app/auth.py
# auth.py
from os import abort

from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import login_user, logout_user, login_required
from werkzeug.security import generate_password_hash, check_password_hash
from .models import *
from . import db
from urllib.parse import urlparse, urljoin
from flask import request, url_for

auth = Blueprint('auth', __name__)


@auth.route('/login')
def login():
    return render_template('login.html')


@auth.route('/signup')
def signup():
    return render_template('signup.html')


@auth.route('/login', methods=['POST'])
def login_post():
    email = request.form.get('email')
    password = request.form.get('password')
    remember = True if request.form.get('remember') else False

    user = User.query.filter_by(email=email).first()

    # check if user actually exists
    # take the user supplied password, hash it, and compare it to the hashed password in database
    if not user or not check_password_hash(user.password, password):
        flash('Please check your login details and try again.')
        return redirect(url_for('auth.login')) # if user doesn't exist or password is wrong, reload the page

    # if the above check passes, then we know the user has the right credentials
    login_user(user, remember=remember)
    next = request.args.get('next')
    if not is_safe_url(next):
        return abort(400)

    return redirect(next or url_for('main.index'))

    return redirect(url_for('main.profile'))


@auth.route('/signup', methods=['POST'])
def signup_post():
    email = request.form.get('email')
    name = request.form.get('name')
    password = request.form.get('password')

    # check if user already exists in database
    user = User.query.filter_by(email=email).first()
    # redirect to signup page to try again if user with same email is found
    if user:
        return redirect(url_for('auth.signup'))
    # create new user using inputted data; password is encrypted from plaintext
    new_user = User(email=email, name=name, password=generate_password_hash(password, method='sha256'))
    # add new user to database
    new_profile = Profile(user=new_user)
    db.session.add(new_profile)
    db.session.commit()

    return redirect(url_for('auth.login'))


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))


def is_safe_url(target):
    ref_url = urlparse(request.host_url)
    test_url = urlparse(urljoin(request.host_url, target))
    return test_url.scheme in ('http', 'https') and \
           ref_url.netloc == test_url.netloc

app/routes/main.py
# main.py
from pprint import pprint

from flask import Blueprint, request, render_template
from flask_login import login_required, current_user
from sqlalchemy import or_, null

from app.models import User, FantasyTeam, Player
from app import db

main = Blueprint('main', __name__)


@main.route('/index')
@main.route('/')
def index():
    return render_template('index.html')


@main.route('/fantasy_team')
@login_required
def fantasy_team():
    players = Player.query.all()
    return render_template('fantasy_team.html', players=players)


@main.route('/fantasy_team', methods=['POST'])
def fantasy_team_post():

    if request.form.get('name') is not None and request.form.get('name') != "":
        current_user.fantasy_team = FantasyTeam(name=request.form.get('name'))

    db.session.commit()

    return render_template('fantasy_team.html')


@main.route('/profile')
@login_required
def profile():
    return render_template('profile.html')


@main.route('/profile', methods=['POST'])
def profile_post():

    if request.form.get('first_name') is not None and request.form.get('first_name') != "":
        current_user.profile.first_name = request.form.get('first_name')
    if request.form.get('last_name') is not None and request.form.get('last_name') != "":
        current_user.profile.last_name = request.form.get('last_name')
    if request.form.get('country') is not None and request.form.get('country') != "":
        current_user.profile.country = request.form.get('country')
    if request.form.get('city') is not None and request.form.get('city') != "":
        current_user.profile.city = request.form.get('city')
    if request.form.get('antipodal_for_id') is not None and request.form.get('antipodal_for_id') != "":
        current_user.antipodal_for_id = request.form.get('antipodal_for_id')
        antipodal_for = User.query.get(request.form.get('antipodal_for_id'))
        antipodal_for.antipodal_for_id = current_user.id

    db.session.commit()

    return render_template('profile.html')

app/templates/base.html
<!-- templates/base.html -->

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Flask Auth Example</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />
    <script src='https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js'></script>
    <script type='text/javascript'
            src ='static/location.js'>
    </script>

</head>

<body>
    <section class="hero is-primary is-fullheight">

        <div class="hero-head">
            <nav class="navbar">
                <div class="container">

                    <div id="navbarMenuHeroA" class="navbar-menu">
                        <div class="navbar-end">
                            <a href="{{ url_for('main.index') }}" class="navbar-item">
                                Home
                            </a>
                            {% if current_user.is_authenticated %}
                            <a href="{{ url_for('main.profile') }}" class="navbar-item">
                                Profile
                            </a>
                            <a href="{{ url_for('main.fantasy_team') }}" class="navbar-item">
                                Team
                            </a>
                            {% endif %}
                            {% if current_user.is_anonymous %}
                            <a href="{{ url_for('auth.login') }}" class="navbar-item">
                                Login
                            </a>
                            <a href="{{ url_for('auth.signup') }}" class="navbar-item">
                                Sign Up
                            </a>
                            {% endif %}
                            {% if current_user.is_authenticated %}
                            <a href="{{ url_for('auth.logout') }}" class="navbar-item">
                                Logout
                            </a>
                            {% endif %}
                            {% if current_user.is_admin==1 %}
                            <a href="{{ url_for('admin.index') }}" class="navbar-item">
                                Admin
                            </a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </nav>
        </div>

        <div class="hero-body">
            <div class="container has-text-centered">
               {% block content %}
               {% endblock %}
            </div>
        </div>
    </section>
</body>

</html>

app/templates/fantasy_team.html
<!-- templates/fantasy_team.html -->

{% extends "base.html" %}

{% block content %}

{% if current_user.fantasy_team %}
<h1 class="title">
    {{ current_user.fantasy_team.name }}
</h1>

{% else %}
<!--create team -->
<div class="column is-4 is-offset-4">
    <h2 class="title">Create your team</h2>
    <div class="box">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <div class="notification is-danger">
            {{ messages[0] }}. Go to <a href="{{ url_for('auth.login') }}">login page</a>.
        </div>
        {% endif %}
        {% endwith %}

        <form method="POST" action="/fantasy_team">

            <div class="field">
                <div class="control">
                    Choose a name for your team:
                    <input class="input is-large" type="text" name="name"
                        {% if current_user.profile.first_name is not none%}
                        placeholder={{current_user.fantasy_team.name}} {% else %} placeholder="Name" {% endif %}
                        autofocus="">
                </div>
            </div>

            <button class="button is-block is-info is-large is-fullwidth">Save</button>
        </form>
    </div>
</div>


{% endif %}


<nav class="level">
    <div class="level-left">

    </div>
    <div class="level-right">
        <div class="level-item">
            <nav class="panel">
                <p class="panel-heading">
                    Players
                </p>
                <div class="panel-block">
                    <p class="control has-icons-left">
                        <input class="input" type="text" placeholder="Search">
                        <span class="icon is-left">
                            <i class="fas fa-search" aria-hidden="true"></i>
                        </span>
                    </p>
                </div>
                <p class="panel-tabs">
                    <a class="is-active">All</a>
                    <a>Chasers</a>
                    <a>Beaters</a>
                </p>
                {% for player in players %}
                <a class="panel-block is-active">
                    <span class="panel-icon">
                        <i class="fas fa-book" aria-hidden="true"></i>
                    </span>
                    {{ player.first_name }}
                </a>
                {% endfor %}
            </nav>
        </div>
    </div>
</nav>
{% endblock %}

app/templates/index.html
<!-- templates/index.html -->

{% extends "base.html" %}

{% block content %}
<h1 class="title">
  Fantasy PLQ
</h1>
<h2 class="subtitle">
  The first online, real-time quidditch fantasy league game.
</h2>
{% endblock %}

app/templates/profile.html
<!-- templates/profile.html -->

{% extends "base.html" %}

{% block content %}
<h1 class="title">
<!--  Welcome, {{ current_user.name }}!-->
</h1>
<div class="column is-4 is-offset-4">
    <h2 class="title">You can edit your profile here</h2>

<!--    <a class="button is-primary is-inverted is-outlined"-->
<!--       onclick="getLocation()"-->
<!--       style="margin-bottom: 30px">-->

<!--        Fill your location details automatically-->

<!--    </a>-->

    <form method="POST" action="/find_my_location" id="form3">
        <input type="hidden" id="country_field" name="country">
        <input type="hidden" id="city_field" name="city">
    </form>

    <div class="box">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="notification is-danger">
                {{ messages[0] }}. Go to <a href="{{ url_for('auth.login') }}">login page</a>.
            </div>
        {% endif %}
        {% endwith %}


        <form method="POST" action="/profile">

            <div class="field">
                <div class="control">
                    First Name
                    <input class="input is-large" type="text" name="first_name"
                           {% if current_user.profile.first_name is not none%}
                           placeholder={{current_user.profile.first_name}}
                           {% else %}
                           placeholder="First Name"
                           {% endif %}
                           autofocus=""
                    >
                </div>
            </div>

            <div class="field">
                <div class="control">
                    Last Name
                    <input class="input is-large" type="text" name="last_name"
                           {% if current_user.profile.last_name is not none%}
                           placeholder={{current_user.profile.last_name}}
                           {% else %}
                           placeholder="Last Name"
                           {% endif %}
                           autofocus=""
                    >
                </div>
            </div>

            <button class="button is-block is-info is-large is-fullwidth">Save</button>
        </form>
    </div>
</div>
{% endblock %}

app/templates/signup.html
<!-- templates/signup.html -->

{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">


    <h3 class="title">Sign Up</h3>
    <div class="box">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="notification is-danger">
                {{ messages[0] }}. Go to <a href="{{ url_for('auth.login') }}">login page</a>.
            </div>
        {% endif %}
        {% endwith %}
        <form method="POST" action="/signup">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="email" name="email" placeholder="Email" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="username" placeholder="Username" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="password" name="password" placeholder="Password">
                </div>
            </div>

            <button class="button is-block is-info is-large is-fullwidth">Sign Up</button>
        </form>
    </div>
</div>
{% endblock %}